
### Create a new survey
POST http://localhost:8080/api/v1/survey
Content-Type: application/json

{
  "title": "test survey"
}

### Get all surveys
GET http://localhost:8080/api/v1/survey



### Add item to survey
POST http://localhost:8080/api/v1/survey/items
Content-Type: application/json

{
  "questionStem": "This is another question???",
  "possibleAnswers": [
    "Answer 1",
    "Answer 2",
    "Answer 3"
  ],
  "correctAnswer": "Answer 1"
}

### Get survey by id
GET http://localhost:8080/api/v1/survey/1


### Get all survey items
GET http://localhost:8080/api/v1/survey/items

### Get survey item by id
GET http://localhost:8080/api/v1/survey/items/4

### associate item with survey
POST http://localhost:8080/api/v1/survey/map
Content-Type: application/json

{
  "surveyId": 1,
  "itemId": 4
}

### Create a survey instance for a user
POST http://localhost:8080/api/v1/survey/newInstance
Content-Type: application/json

{
  "surveyId": 1,
  "username": "Doug"
}

### Get survey instance (by id)
GET http://localhost:8080/api/v1/survey/instance/4


### Submit incorrect answer for a user
PATCH http://localhost:8080/api/v1/survey/instance/answer
Content-Type: application/json

{
  "username": "Jake",
  "userAnswer": "NOT THE CORRECT ANSWER",
  "itemId": 4
}

### Submit correct answer for a user
PATCH http://localhost:8080/api/v1/survey/instance/answer
Content-Type: application/json

{
  "username": "Jake",
  "userAnswer": "Answer 2",
  "itemId": 4
}

### Get survey instances by state (created)
GET http://localhost:8080/api/v1/survey/instance?state=CREATED

### Get survey instances by state (with null state)
GET http://localhost:8080/api/v1/survey/instance