spring:
  application:
    name: "survey_api"

  datasource:
    url: jdbc:postgresql://localhost:5435/survey_db
    username: survey_user
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
